package com.sakura.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ID
     *
     * @mbg.generated Thu Nov 14 21:46:59 CST 2024
     *  <id property="id" column="ID"/>
     *         <result property="userName" column="USER_NAME"/>
     *         <result property="phone" column="PHONE"/>
     *         <result property="loginName" column="LOGIN_NAME"/>
     *         <result property="loginPwd" column="LOGIN_PWD"/>
     */
    private Integer ID;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USER_NAME
     *
     * @mbg.generated Thu Nov 14 21:46:59 CST 2024
     */
    private String USER_NAME;

    /**
     * Database Column Remarks:
     *   电话号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PHONE
     *
     * @mbg.generated Thu Nov 14 21:46:59 CST 2024
     */
    private String PHONE;

    /**
     * Database Column Remarks:
     *   登录名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_NAME
     *
     * @mbg.generated Thu Nov 14 21:46:59 CST 2024
     */
    private String LOGIN_NAME;

    /**
     * Database Column Remarks:
     *   登录密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_PWD
     *
     * @mbg.generated Thu Nov 14 21:46:59 CST 2024
     */
    private String LOGIN_PWD;


    public String getLOGIN_PWD() {
        return LOGIN_PWD;
    }

    public void setLOGIN_PWD(String LOGIN_PWD) {
        this.LOGIN_PWD = LOGIN_PWD;
    }

    public String getLOGIN_NAME() {
        return LOGIN_NAME;
    }

    public void setLOGIN_NAME(String LOGIN_NAME) {
        this.LOGIN_NAME = LOGIN_NAME;
    }

    public String getPHONE() {
        return PHONE;
    }

    public void setPHONE(String PHONE) {
        this.PHONE = PHONE;
    }

    public String getUSER_NAME() {
        return USER_NAME;
    }

    public void setUSER_NAME(String USER_NAME) {
        this.USER_NAME = USER_NAME;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    @Override
    public String toString() {
        return "User{" +
                "ID=" + ID +
                ", USER_NAME='" + USER_NAME + '\'' +
                ", PHONE='" + PHONE + '\'' +
                ", LOGIN_NAME='" + LOGIN_NAME + '\'' +
                ", LOGIN_PWD='" + LOGIN_PWD + '\'' +
                '}';
    }
}