package com.ynnz.pojo;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_account
 */
public class Account {
	
	private String sexStr;//描述‘男’ ‘女’的性别
	
    public String getSexStr() {
    	sexStr="男";
    	if("1".equals(this.sex)) {
    		sexStr = "女";
    	}
    	if("2".equals(this.sex)) {
    		sexStr = "男";
    	}
		return sexStr;
	}

	public void setSexStr(String sexStr) {
		this.sexStr = sexStr;
	}

	/**
     * Database Column Remarks:
     *   主键ID，唯一标识账户，方便程序中使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   卡号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.NUMBER
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String number;

    /**
     * Database Column Remarks:
     *   账户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String name;

    /**
     * Database Column Remarks:
     *   账户余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.MONEY
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.TYPE_ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.SEX
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.CARD_PICTURE
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String cardPicture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.ID
     *
     * @return the value of t_account.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.ID
     *
     * @param id the value for t_account.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.NUMBER
     *
     * @return the value of t_account.NUMBER
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.NUMBER
     *
     * @param number the value for t_account.NUMBER
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.NAME
     *
     * @return the value of t_account.NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.NAME
     *
     * @param name the value for t_account.NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.MONEY
     *
     * @return the value of t_account.MONEY
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.MONEY
     *
     * @param money the value for t_account.MONEY
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.TYPE_ID
     *
     * @return the value of t_account.TYPE_ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.TYPE_ID
     *
     * @param typeId the value for t_account.TYPE_ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.SEX
     *
     * @return the value of t_account.SEX
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.SEX
     *
     * @param sex the value for t_account.SEX
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.CARD_PICTURE
     *
     * @return the value of t_account.CARD_PICTURE
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getCardPicture() {
        return cardPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.CARD_PICTURE
     *
     * @param cardPicture the value for t_account.CARD_PICTURE
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setCardPicture(String cardPicture) {
        this.cardPicture = cardPicture == null ? null : cardPicture.trim();
    }
}