package com.ynnz.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_type
 */
public class Type {
    /**
     * Database Column Remarks:
     *   主键ID，唯一标识账户类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   类型名称，如：一类户，二类户，VIP户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.TYPE_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String typeName;

    /**
     * Database Column Remarks:
     *   账户类型顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.TYPE_ORDER
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private Boolean typeOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.ID
     *
     * @return the value of t_type.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.ID
     *
     * @param id the value for t_type.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.TYPE_NAME
     *
     * @return the value of t_type.TYPE_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.TYPE_NAME
     *
     * @param typeName the value for t_type.TYPE_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.TYPE_ORDER
     *
     * @return the value of t_type.TYPE_ORDER
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public Boolean getTypeOrder() {
        return typeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.TYPE_ORDER
     *
     * @param typeOrder the value for t_type.TYPE_ORDER
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setTypeOrder(Boolean typeOrder) {
        this.typeOrder = typeOrder;
    }
}