package com.ynnz.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USER_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   电话号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PHONE
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   登录名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   登录密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_PWD
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    private String loginPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ID
     *
     * @return the value of t_user.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ID
     *
     * @param id the value for t_user.ID
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USER_NAME
     *
     * @return the value of t_user.USER_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USER_NAME
     *
     * @param userName the value for t_user.USER_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PHONE
     *
     * @return the value of t_user.PHONE
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PHONE
     *
     * @param phone the value for t_user.PHONE
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOGIN_NAME
     *
     * @return the value of t_user.LOGIN_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOGIN_NAME
     *
     * @param loginName the value for t_user.LOGIN_NAME
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOGIN_PWD
     *
     * @return the value of t_user.LOGIN_PWD
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOGIN_PWD
     *
     * @param loginPwd the value for t_user.LOGIN_PWD
     *
     * @mbg.generated Tue Jun 08 13:45:42 CST 2021
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }
}